gyhuhgbznv baseURL: http://example.org/
languageCode: en-us
title: Fonti Kar
theme: hugo-material

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

markup:
  goldmark:
    renderer:
      unsafe: true
